### ISSUE TITLE
Mux H264 NALs into fragmented MP4

### ISSUE THREAD

**Issue by david74chou** [videojs/mux.js#75] opened 2016-03-30 10:19 UTC
Hi all,

If I got H264 NALs streaming from WebSocket or WebRTC data channel, could I use mux.js to mux them into fragmented MP4 and make browser to play with MSE ?

I think the muxing part should be ready and I only need to feed those NALs into the muxer. 
Is it doable ?

Thanks

**Comment by dmlap** [comment] 2016-03-30 15:50
Seems plausible but we haven't tried anything like that directly. I would take a look at the [mp4 generator](https://github.com/videojs/mux.js/blob/db6ac31d2e286dea85cb985a96eb8ec023c8f3c1/lib/mp4/mp4-generator.js). You'll need to build the sample table and some other track-related metadata by hand.

**Comment by dmlap** [comment] 2016-04-14 18:56
Closing this one since it seems like it should work. Feel free to keep commenting here if you have additional questions. (It would be great to hear how it worked out!)

**Closed by dmlap** 2016-04-14 18:56 UTC

**Comment by Serveurperso** [comment] 2019-04-25 20:14
Need the same. I use Broadway to make an universal low latency robotics control system. (about 0.1-0.3 second latency from a LTE/4G robot to a LTE/4G Web Browser / through a dedicated server)

I need to explore the H.264 to MP4. What about the latency with the HTML5 MP4 player ?

**Comment by zhubinsheng** [comment] 2020-10-14 08:01
> 需要一样。我使用Broadway制作了通用的低延迟机器人控制系统。（从LTE / 4G机械手到LTE / 4G Web浏览器/通过专用服务器的延迟大约为0.1-0.3秒）
> 
> 我需要探索H.264到MP4。HTML5 MP4播放器的延迟时间如何？

Have you tried this method? Can it work? Thank you in advance for your reply

**Comment by Serveurperso** [comment] 2020-10-14 08:31
Yes it work, project is now advanced, you can look here (no ads / non lucrative website). https://www.vigibot.com/

**Comment by zhubinsheng** [comment] 2020-10-14 08:46
> 是的，它可以正常工作，项目现在已经完成，您可以在这里查看（无广告/非盈利网站）。https://www.vigibot.com/

OK, I have read this website, and I sent an email to your email, just to ask for some technical knowledge, such as why do you use baordway to decode? Instead of using it wfs.js perhaps mux.js 。  other Do you have any opinions on audio and video synchronization. Thank you in advance for your reply

**Comment by Serveurperso** [comment] 2020-10-14 12:14
No audio synchronization required for our usage, all arrive the fastest possible (better for realtime robotics !)

**Comment by zhubinsheng** [comment] 2020-10-14 12:18
> No audio synchronization required for our usage, all arrive the fastest possible (better for realtime robotics !)

Is it convenient to disclose the chip you use? And what is the actual frame rate? By the way, do I still see that the labels on your website are the result of machine learning recognition

**Comment by Serveurperso** [comment] 2020-10-14 12:21
We don't use chip, robot are Raspberry PI 2/3/4, we can offer support to make robot but not to reproduce the website.

**Comment by Serveurperso** [comment] 2020-10-14 12:24
Computer vision work on any >= PI 3 A/B+ @ 30FPS with realtime low latency view on the website
