### ISSUE TITLE
"muxjs is not defined" error when using mux.min.js

### ISSUE THREAD

**Issue by mrlika** [videojs/mux.js#173] opened 2018-01-03 17:07 UTC
With 'mux.js' everything is Ok. Looks like minified version doesn't expose 'window.muxjs' object

**Comment by forbesjo** [comment] 2018-09-14 14:39
Looks like this is caused by `bundle-collapser`, I'll get a fix for this soon

**Comment by dalecurtis** [comment] 2019-05-02 21:44
Is there any workaround for this? It makes the official minified versions useless with ShakaPlayer.

**Comment by dalecurtis** [comment] 2019-05-02 21:57
(Manually uglifying the unminified version seems to work).

**Comment by joeyparrish** [comment] 2019-05-13 17:57
@forbesjo, can you point us in the right direction to fix this?  I'd be happy to submit a PR.

**Comment by dalecurtis** [comment] 2019-05-13 18:11
I think just accepting this pull request would fix it: https://github.com/videojs/mux.js/pull/263 but I'm not sure.

**Comment by joeyparrish** [comment] 2019-05-13 19:19
I tried #263, but it doesn't seem to help.

If I break down the build steps, I find that the collapse step is where the "window" references disappear.

**Comment by joeyparrish** [comment] 2019-05-13 19:40
Just getting rid of bundle-collapser fixed it, at a cost of about 2.6kB in size at the end.

 - Unminified: 280,538 bytes
 - "Collapsed" & minified, but unusable: 87,790 bytes
 - Just minified, but usable: 90,480 bytes

**Comment by joeyparrish** [comment] 2019-05-13 20:08
PR #266 is up, assuming this solution is acceptable to the maintainers.

**Comment by gkatsev** [comment] 2019-05-13 20:12
That's actually kind of surprising, I'd have expected bundle-collapser to keep `window` exports.
I'm not against getting rid of it but having keeping it and having it usable is definitely the best case scenario.

**Comment by gkatsev** [comment] 2019-05-13 20:14
Looks like it's a known (and old issue): https://github.com/substack/bundle-collapser/issues/5
Sounds like maybe just switching to using it as a browserify plugin makes it work? I'll give it a shot.

**Comment by gkatsev** [comment] 2019-05-13 20:27
@joeyparrish hey, can you give this PR a shot? https://github.com/videojs/mux.js/pull/267

**Comment by joeyparrish** [comment] 2019-05-13 20:31
Confirmed that #267 works for me.  Thanks!

**Closed** 2019-05-13 20:34 UTC
Labels: bug

**Comment by gkatsev** [comment] 2019-05-13 20:35
mux.js 5.1.3 published with the fix.

**Comment by gkatsev** [comment] 2019-05-13 20:35
Thanks for everyone's (extreme) patience on this one!

**Comment by joeyparrish** [comment] 2019-05-13 21:08
Thanks!
